[tasks.run-server]
run = 'wrangler dev "$@"'

[tasks.test]
run = '''
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
python -m pytest --cov${PYTEST_COV-} \
    --cov-report=term-missing:skip-covered --verbose "$@"
'''